import Head from 'next/head';
import React, { useState } from 'react';
import { lightTheme, darkTheme } from '../styles/ThemeConfig';
import { ThemeProvider } from 'styled-components';
import { GlobalStyles } from '../styles/ThemeConfig';
import { Switch } from '@nextui-org/react';
import { MoonIcon, SunIcon } from '@primer/octicons-react';
import { NavStyle } from '../styles/NavStyle';

export default function Home() {
  const [theme, setTheme] = useState(true);
  return (
    <ThemeProvider theme={theme ? lightTheme : darkTheme}>
      <GlobalStyles />
      <Head>
        <title lang="es">Create Next App</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <NavStyle>
        <div className="switchMode">
          {theme ? (
            <SunIcon size={24} className="iconMode" />
          ) : (
            <MoonIcon size={24} className="iconMode" />
          )}
          <Switch
            checked={!theme}
            onChange={() => (theme ? setTheme(false) : setTheme(true))}
          />
        </div>
      </NavStyle>
    </ThemeProvider>
  );
}
